import localFont from 'next/font/local';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';

const archivo = localFont({
  src: './fonts/ArchivoVF.ttf',
  variable: '--archivo-font',
  weight: '100 200 300 400 500 600 700',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${archivo.variable} font-sans antialiased`}
      >
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
